services:
  - type: web
    name: mordipets
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
